# nixpacks.toml

# Phase 1: Setup - Install necessary system packages/tools
[phases.setup]
# Add the 'infisical' Nix package.
# Note: Check the Nixpkgs search (search.nixos.org) if 'infisical' isn't the exact name; sometimes it might be 'infisical-cli'. 'infisical' is the common name currently.
pkgs = ["infisical"]

# Phase 2: Install - Install language-specific dependencies
[phases.install]
# Override the default install command (which would just be 'bun install')
# This command first exports secrets from Infisical to a .env file,
# and only if that succeeds (due to &&), it runs 'bun install'.
cmds = ["npx @infisical/cli run --env=dev --domain=https://secrets.sikka.io --projectId=b1c8c504-ff56-43bb-9226-b1035bf94426 --token=$INFISICAL_TOKEN bun install"]

# You might also have build and start phases defined here
[phases.build]
cmds = ["npx @infisical/cli run --env=dev --domain=https://secrets.sikka.io --projectId=b1c8c504-ff56-43bb-9226-b1035bf94426 --token=$INFISICAL_TOKEN bun run build"]

[start]
cmd = "npx @infisical/cli run --env=dev --domain=https://secrets.sikka.io --projectId=b1c8c504-ff56-43bb-9226-b1035bf94426 --token=$INFISICAL_TOKEN bun run start"
