services:
  tanad:
    image: ghcr.io/zaaakher/tanad:latest
    container_name: tanad-app
    restart: always
    ports:
      - "3037:3037"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_APP_URL}/api
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - HOST=0.0.0.0  # Add this to ensure Next.js binds to all interfaces
      - PORT=3037  # Explicitly set the port to 3037
    platform: linux/amd64
